### ISSUE TITLE
Scraping error, when duration is more than 2 minutes

### ISSUE THREAD

**Issue by kago-dk** [hudeldudel/postman-exporter#15]
It seems like Prometheus is failing to scrape the metrics from postman-exporter when the scrape duration is more than 2 minutes, and an error is returned as: `Get "http://postman-exporterserver:3000/probe/LargeData": EOF`.

I can run the same postman-exporter tests from the browser without a timeout(?) if I run it in the browser.

I tried to set the scrape timeout to 15 minutes in Prometheus without any luck.

Any hints?

**Comment by hudeldudel** [comment]
I haven't tried to reproduce this yet.

There are basically two timouts that can occur.
1. Newman timeouts
2. Prometheus timeout

It looks like you are hitting the second one.
Please try to set `scrape_timeout` in your Prometheus scrape configuration to a suitable value.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

The there are also some timeouts you can configure in the probe options for Newman to run your Postman collection.
* `timeout`
* `timeoutRequest`
* `timeoutScript`

See here for details: https://github.com/postmanlabs/newman#newmanrunoptions-object--callback-function--run-eventemitter

Please let me know whether one of the configurations was able to fix the error.

**Comment by kago-dk** [comment]
@hudeldudel Thanks for the quick guidance. It looks like it is Nodejs, which closes the connection after two minutes, so I am playing with the timeout value (based on the example and comments on: https://www.derpturkey.com/increase-request-timeout-for-express-4/ and https://stackoverflow.com/questions/32882507/nodejs-and-express-server-closes-connection-after-2-minutes).

main.js
`// app.listen(config.serverPort, () => logger.info(`postman exporter running on port ${config.serverPort}`));
// start the server
const server = app.listen(config.serverPort, () => logger.info(`postman exporter running on port ${config.serverPort}`));

// increase the timeout to 8 minutes
server.timeout = 480000;`

I am not a developer, so my code is probably not the best way of doing it.

**Comment by hudeldudel** [comment]
I hadn't thought of the express web server's timeout times when I last commented. 

I could make the value easily configurable so that no code adjustments are necessary for the user.

**Comment by kago-dk** [comment]
It would make sense to make it configurable. Since my issue has been resolved by my modification, feel to close the issue now or when you have made it configurable.

**Comment by hudeldudel** [comment]
It took a while, but I now created a new release that allows the configuration of the timeout.

https://github.com/hudeldudel/postman-exporter/releases/tag/v0.2.0
