### ISSUE TITLE
Which js file can get the detailed information of http response, such as body, return status

### ISSUE THREAD

**Issue by LiuQhahah** [hudeldudel/postman-exporter#2]
Which js file can get the detailed information of http response, such as body, return status？

**Comment by LiuQhahah** [comment]
I  use “Test” in  Postman

**Comment by hudeldudel** [comment]
The intention is to write tests in Posman and scrape metrics from /metrics endpoint.
If you want to check specific information from the response, you should write tests for that information. You can then check for the test result and create alerts/dashboards from it using Prometheus/Alertmanager/Grafana.
