### ISSUE TITLE
Use of iterationData in probes.js

### ISSUE THREAD

**Issue by kago-dk** [hudeldudel/postman-exporter#9]
I am not sure, if the postman-exporter does not support the use of iterationData or if it is a configuration error on my part. If I try to use a configuration such as shown, then the Chrome browser is just spinning when opening http://servername:3000/probe/example.

```
module.exports = {
    "example": {
        options: {
            collection: require('./example.json'),
	    iterationData: './abc.csv',
	    iterationCount: 1
        }
    }
};
```

As soon as I remove the iterationData line from the configuration, then I am able to get metrics back. The example is oversimplied and I recognize that the example.json is not using the data in the abc.csv. A file, which just looks like this:

```
Code
abc
```

**Comment by hudeldudel** [comment]
Sadly, configuration is a bit counter intuitive and logging does not help.

Please try 
`iterationData: __dirname + '/' + 'abc.csv',`
to use abc.csv located in config/

**Comment by hudeldudel** [comment]
@kago-dk 

Can you confirm, that iteration data is working for you if you use

- a path based on the root of the project (config/abc.csv)
- or an absolute path e. g. /app/config/abc.csv
- or the __dirname to point to the directory where config.js is located?

**Comment by kago-dk** [comment]
Thanks for your help @hudeldudel, it works as suggested.
